package com.example.backend.model.enums;

public enum NotificationType {
    DEMANDE_SUBMITTED_BY_EMPLOYE,
    DEMANDE_MODIFIED_BY_EMPLOYE,
    DEMANDE_CANCELLED_BY_EMPLOYE,
    DEMANDE_VALIDATED_BY_RESPONSABLE,
    DEMANDE_MODIFIED_BY_RESPONSABLE,
    DEMANDE_REFUSED_BY_RESPONSABLE,
    DEMANDE_VALIDATED_BY_DG,
    DEMANDE_REFUSED_BY_DG,
    DEMANDE_VALIDATED_DG_FOR_RH
}
