spring.application.name=backend

# PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-fancy-thunder-alprf8kd-pooler.c-3.eu-central-1.aws.neon.tech/DB_Sophatel?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pAqm3Dkf2FKH

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port Spring Boot
server.port=8081

# JWT
jwt.secret=une-cle-secrete-longue-et-securisee-pour-sophatel-auth-jwt-2026
jwt.expiration=28800000
